// Generated by LiveScript 1.2.0
var _;
_ = require('../index.js');
exports.urlResolve = function(it){
  it.strictEqual(_.urlResolve('/a/b/c', '../index.html'), '/a/index.html');
  return it.done();
};
exports.urlParse = function(it){
  it.strictEqual(_.urlParse('http://farzher.com').host, 'farzher.com');
  return it.done();
};
exports.parsedToUri = function(it){
  it.strictEqual(_.parsedToUri(_.urlParse('http://farzher.com')), '/');
  return it.done();
};
exports.urlToUri = function(it){
  it.strictEqual(_.urlToUri('http://farzher.com'), '/');
  return it.done();
};
exports.regexMatch = function(it){
  it.strictEqual(_.regexMatch(/a/g, 'ababab').length, 3);
  it.strictEqual(_.regexMatch(/does not exist/, 'ababab').length, 0);
  return it.done();
};
exports.regexExec = function(it){
  var temp;
  temp = _.regexExec(/a(b)/g, 'ababab');
  it.strictEqual(temp.length, 3);
  it.strictEqual(temp[2][0], 'ab');
  it.strictEqual(temp[2][1], 'b');
  temp = _.regexExec(/href="(.*?)"/g, '<a id="pants" href="something.com">lol</a>', 1);
  it.strictEqual(temp[0], 'something.com');
  return it.done();
};
exports.shuffle = function(it){
  var arr, shuffled, i$, len$, v, index;
  arr = [1, 2, 3, 'a', 'b', 'c'];
  shuffled = _.shuffle(_.clone(arr));
  for (i$ = 0, len$ = arr.length; i$ < len$; ++i$) {
    v = arr[i$];
    index = _.elemIndex(v, shuffled);
    it.ok(index != null, 'Every element in the original array should be in the shuffled array');
  }
  return it.done();
};